# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "personal-centos"
  config.vm.network :private_network, ip: "192.168.33.31"
  #config.vm.synced_folder ".", "/vagrant", type: "virtualbox"   # for Windows 10
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", 1536]
  end

  config.vm.provision "shell", inline: <<-SHELL
    #
    # Initial Settings
    #
    sudo setenforce 0
    sudo sed -e "s/enforcing/disabled/g" /etc/selinux/config
    sudo timedatectl set-timezone Asia/Tokyo
    sudo yum update

    #
    # Install Tools
    #
    sudo yum install -y git tmux vim curl wget
  SHELL
end
