# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"

  config.vm.define "fasthandle" do |fasthandle|
    fasthandle.vm.hostname = "fasthandle"
    fasthandle.vm.network :private_network, ip: "192.168.33.90"
    #fasthandle.vm.synced_folder ".", "/vagrant", type: "virtualbox"   # for Windows 10
    fasthandle.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", 1536]
    end
    fasthandle.vm.provision "shell", inline: <<-SHELL
      #
      # Initial Settings
      #
      sudo setenforce 0
      sudo sed -e "s/enforcing/disabled/g" /etc/selinux/config
      sudo timedatectl set-timezone Asia/Tokyo
      #sudo yum update

      #
      # Install Tools
      #
      #sudo yum install -y git tmux vim curl wget
    SHELL
  end

  config.vm.define "server1" do |server1|
    server1.vm.hostname = "server1"
    server1.vm.network :private_network, ip: "192.168.33.91"
    server1.vm.provision "shell", inline: <<-SHELL
      #
      # Initial Settings
      #
      sudo setenforce 0
      sudo sed -e "s/enforcing/disabled/g" /etc/selinux/config
      sudo timedatectl set-timezone Asia/Tokyo
      #sudo yum update

      #
      # Install Tools
      #
      #sudo yum install -y git tmux vim curl wget
    SHELL
  end

  config.vm.define "server2" do |server2|
    server2.vm.hostname = "server2"
    server2.vm.network :private_network, ip: "192.168.33.92"
    server2.vm.provision "shell", inline: <<-SHELL
      #
      # Initial Settings
      #
      sudo setenforce 0
      sudo sed -e "s/enforcing/disabled/g" /etc/selinux/config
      sudo timedatectl set-timezone Asia/Tokyo
      #sudo yum update

      #
      # Install Tools
      #
      #sudo yum install -y git tmux vim curl wget
    SHELL
  end
end
